In [1]:
import numpy as np

def det_2x2(A):
    return A[0,0]*A[1,1] - A[0,1]*A[1,0]

def det_3x3(A):
    a = A[0,0]; b = A[0,1]; c = A[0,2]
    d = A[1,0]; e = A[1,1]; f = A[1,2]
    g = A[2,0]; h = A[2,1]; i = A[2,2]

    return a*e*i + b*f*g + c*d*h - c*e*g - b*d*i - a*f*h

A2 = np.array([[1,2],
               [3,4]])

A3 = np.array([[1,2,3],
               [4,5,6],
               [7,8,10]])

print("det 2x2 =", det_2x2(A2))
print("numpy =", np.linalg.det(A2))

print("\ndet 3x3 =", det_3x3(A3))
print("numpy =", np.linalg.det(A3))

det 2x2 = -2
numpy = -2.0000000000000004

det 3x3 = -3
numpy = -2.9999999999999996


In [2]:
def det_gauss(A):
    A = A.astype(float)
    n = len(A)
    det = 1

    for i in range(n):
        if A[i,i] == 0:
            return 0

        for j in range(i+1, n):
            fator = A[j,i] / A[i,i]
            A[j] = A[j] - fator * A[i]

    for i in range(n):
        det *= A[i,i]

    return det

B = np.array([[2,1,3],
              [1,0,2],
              [4,1,8]])

print("det (Gauss) =", det_gauss(B))
print("numpy =", np.linalg.det(B))

det (Gauss) = -1.0
numpy = -1.0


In [3]:
A = np.array([[1,2],
              [3,4]])

inv_A = np.linalg.inv(A)

print("A =")
print(A)

print("\nA inversa =")
print(inv_A)

print("\nA @ A_inv =")
print(A @ inv_A)

A =
[[1 2]
 [3 4]]

A inversa =
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv =
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [4]:
I = np.eye(2)

print("A @ A_inv =")
print(A @ inv_A)

print("\nÉ igual à identidade?")
print(np.allclose(A @ inv_A, I))

A @ A_inv =
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

É igual à identidade?
True
