In [ ]:
import numpy as np
import numpy.linalg as la

def mostrar(A, msg=""):
    print(msg)
    print(np.round(A).astype(int))
    print("-" * 40)

def escalonar(Ab, debug=True):
    A = Ab.astype(float)
    n, m = A.shape

    for i in range(min(n, m-1)):

        max_row = i + np.argmax(abs(A[i:, i]))
        A[[i, max_row]] = A[[max_row, i]]

        if debug:
            mostrar(A, f"Pivot coluna {i}")

        for j in range(i+1, n):
            if A[i, i] != 0:
                fator = A[j, i] / A[i, i]
                A[j, i:] -= fator * A[i, i:]

                if debug:
                    mostrar(A, f"Eliminando linha {j}")

    return A

def substituicao_retroativa(U):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        if np.isclose(U[i, i], 0):
            raise ValueError("Sistema não SPD")

        x[i] = U[i, -1] - np.sum(U[i, i+1:n] * x[i+1:n])
        x[i] /= U[i, i]

    return x

def classificar_sistema(A, b):
    A = np.array(A, float)
    b = np.array(b, float).reshape(-1, 1)

    Ab = np.hstack([A, b])

    rank_A = np.linalg.matrix_rank(A)
    rank_Ab = np.linalg.matrix_rank(Ab)
    n = A.shape[1]

    if rank_A != rank_Ab:
        return "SI"
    elif rank_A < n:
        return "SPI"
    else:
        return "SPD"


# ===== SISTEMA =====
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
], float)

b = np.array([8, -11, -3], float)

Ab = np.hstack([A, b.reshape(-1,1)])
U = escalonar(Ab, debug=True)

sol = substituicao_retroativa(U)

print("Solução:", np.round(sol).astype(int))
print("Classificação:", classificar_sistema(A, b))


# ===== OUTROS =====
A_si = np.array([[1, 1],
                 [2, 2]], float)
b_si = np.array([3, 5], float)

print("SI:", classificar_sistema(A_si, b_si))


A_spi = np.array([[1, 2, 3],
                  [2, 4, 6]], float)

b_spi = np.array([1, 2], float)

print("SPI:", classificar_sistema(A_spi, b_spi))


# ===== COMPARAÇÃO =====
x_np = la.solve(A, b)
print("NumPy:", np.round(x_np).astype(int))

x_gauss = substituicao_retroativa(escalonar(np.hstack([A, b.reshape(-1,1)]), debug=False))
print("Gauss:", np.round(x_gauss).astype(int))

print("Verificação:", np.allclose(A @ sol, b))

Pivot coluna 0
[[ -3.  -1.   2. -11.]
 [  2.   1.  -1.   8.]
 [ -2.   1.   2.  -3.]]
----------------------------------------
Eliminando linha 1
[[ -3.     -1.      2.    -11.   ]
 [  0.      0.333   0.333   0.667]
 [ -2.      1.      2.     -3.   ]]
----------------------------------------
Eliminando linha 2
[[ -3.     -1.      2.    -11.   ]
 [  0.      0.333   0.333   0.667]
 [  0.      1.667   0.667   4.333]]
----------------------------------------
Pivot coluna 1
[[ -3.     -1.      2.    -11.   ]
 [  0.      1.667   0.667   4.333]
 [  0.      0.333   0.333   0.667]]
----------------------------------------
Eliminando linha 2
[[ -3.     -1.      2.    -11.   ]
 [  0.      1.667   0.667   4.333]
 [  0.      0.      0.2    -0.2  ]]
----------------------------------------
Pivot coluna 2
[[ -3.     -1.      2.    -11.   ]
 [  0.      1.667   0.667   4.333]
 [  0.      0.      0.2    -0.2  ]]
----------------------------------------
Solução: [ 2.  3. -1.]
Classificação: SPD (solução ú