In [5]:
import numpy as np

def cramer_2x2(A, b):
    detA = np.linalg.det(A)

    A1 = A.copy()
    A1[:, 0] = b

    A2 = A.copy()
    A2[:, 1] = b

    x = np.linalg.det(A1) / detA
    y = np.linalg.det(A2) / detA

    return np.array([x, y])


def cramer_3x3(A, b):
    detA = np.linalg.det(A)

    solucao = []

    for i in range(3):
        Ai = A.copy()
        Ai[:, i] = b
        solucao.append(np.linalg.det(Ai) / detA)

    return np.array(solucao)


A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 6])

print("Sistema 2x2")
print("Cramer =")
print(cramer_2x2(A, b))

print("\nNumPy =")
print(np.linalg.solve(A, b))


A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

b = np.array([8, -11, -3])

print("\nSistema 3x3")
print("Cramer =")
print(cramer_3x3(A, b))

print("\nNumPy =")
print(np.linalg.solve(A, b))

Sistema 2x2
Cramer =
[1.8 1.4]

NumPy =
[1.8 1.4]

Sistema 3x3
Cramer =
[ 2.  3. -1.]

NumPy =
[ 2.  3. -1.]


In [6]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 1, 1],
              [4, -6, 0],
              [-2, 7, 2]])

P, L, U = lu(A)

print("Matriz A:")
print(A)

print("\nP:")
print(P)

print("\nL:")
print(L)

print("\nU:")
print(U)

print("\nPA:")
print(P @ A)

print("\nLU:")
print(L @ U)

print("\nPA = LU ?")
print(np.allclose(P @ A, L @ U))

det = np.prod(np.diag(U))

print("\nDeterminante:")
print(det)

Matriz A:
[[ 2  1  1]
 [ 4 -6  0]
 [-2  7  2]]

P:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

L:
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  1.   1. ]]

U:
[[ 4. -6.  0.]
 [ 0.  4.  1.]
 [ 0.  0.  1.]]

PA:
[[ 4. -6.  0.]
 [ 2.  1.  1.]
 [-2.  7.  2.]]

LU:
[[ 4. -6.  0.]
 [ 2.  1.  1.]
 [-2.  7.  2.]]

PA = LU ?
True

Determinante:
16.0
