In [ ]:
import numpy as np
import matplotlib.pyplot as plt

#T1

def det_2x2(A):
    return A[0][0]*A[1][1] - A[0][1]*A[1][0]

def det_3x3_sarrus(A):
    a,b,c = A[0]
    d,e,f = A[1]
    g,h,i = A[2]
    pos = a*e*i + b*f*g + c*d*h
    neg = c*e*g + b*d*i + a*f*h
    return pos - neg

A1 = np.array([[2,3],
               [1,4]])

A2 = np.array([[2,4],[
                1,2]])  

print("det_2x2(A1) =", det_2x2(A1))
print("det_2x2(A2) =", det_2x2(A2))

B1 = np.array([[1,2,3],
               [0,1,4],
               [5,6,0]])

B2 = np.array([[1,2,3],[
                2,4,6],[
                1,1,1]]) 

print("Sarrus(B1) =", det_3x3_sarrus(B1), " | numpy =", np.linalg.det(B1))
print("Sarrus(B2) =", det_3x3_sarrus(B2), " | numpy =", np.linalg.det(B2))

#T2

def det_gauss(A):
    A = A.astype(float).copy()
    n = A.shape[0]
    det = 1
    steps = []

    for i in range(n):
        if A[i][i] == 0:
            for k in range(i+1, n):
                if A[k][i] != 0:
                    A[[i,k]] = A[[k,i]]
                    det *= -1
                    steps.append(A.copy())
                    break

        pivot = A[i][i]
        det *= pivot

        if pivot == 0:
            return 0, steps

        for j in range(i+1, n):
            factor = A[j][i] / pivot
            A[j] -= factor * A[i]
            steps.append(A.copy())

    return det, steps

# Teste 4x4
M = np.array([
    [2,1,3,4],
    [1,0,2,1],
    [3,2,1,5],
    [4,1,0,2]
])

det, steps = det_gauss(M)
print("Determinante =", round(det, 6))
print("Passos =", len(steps))

#T3

def verifica_propriedades():
    A = np.random.randn(3,3)
    B = np.random.randn(3,3)
    k = 5

    print("1) det(AB) =", round(np.linalg.det(A@B), 6), " | det(A)det(B) =", round(np.linalg.det(A)*np.linalg.det(B), 6))
    print("2) det(A^T) =", round(np.linalg.det(A.T), 6), " | det(A) =", round(np.linalg.det(A), 6))
    print("3) det(kA) =", round(np.linalg.det(k*A), 6), " | k^n det(A) =", round((k**3)*np.linalg.det(A), 6))

    # row swap
    A2 = A.copy()
    A2[[0,1]] = A2[[1,0]]
    print("4) Row swap → det =", round(np.linalg.det(A2), 6), " | esperado =", round(-np.linalg.det(A), 6))

    # add multiple of row
    A3 = A.copy()
    A3[1] += 3*A3[0]
    print("5) Add múltiplo → det =", round(np.linalg.det(A3), 6), " | esperado =", round(np.linalg.det(A), 6))

verifica_propriedades()

#T4

def eh_invertivel(A):
    det = np.linalg.det(A)
    cond = np.linalg.cond(A)
    return det != 0, det, cond

A_inv = np.array([[2,1],[1,1]])
A_sing = np.array([[1,2],[2,4]])
A_ill = np.array([[1,1],[1,1]])

for M in [A_inv, A_sing, A_ill]:
    inv, det, cond = eh_invertivel(M)
    print("\nMatriz:\n", M)
    print("Invertível:", inv)
    print("Determinante:", det)
    print("Cond. number:", cond)

#T5

def inversa_gauss_jordan(A):
    n = A.shape[0]
    M = np.hstack([A.astype(float), np.eye(n)])

    for i in range(n):
        pivot = M[i][i]
        if pivot == 0:
            for k in range(i+1, n):
                if M[k][i] != 0:
                    M[[i,k]] = M[[k,i]]
                    pivot = M[i][i]
                    break

        M[i] /= pivot

        for j in range(n):
            if j != i:
                M[j] -= M[j][i] * M[i]

    return M[:, n:]

# Teste
A = np.array([[1,2,3],[0,1,4],[5,6,0]])
invA = inversa_gauss_jordan(A)
print(invA)
print("Verificação A*A^-1 =\n", A @ invA)

#T6

import matplotlib.pyplot as plt

def visualizar_transformacao(A):
    square = np.array([[0,0],[1,0],[1,1],[0,1],[0,0]])
    transformed = square @ A.T

    plt.figure(figsize=(6,6))
    plt.plot(square[:,0], square[:,1], 'b-', label="Unit Square")
    plt.plot(transformed[:,0], transformed[:,1], 'r-', label="Transformed")

    plt.title(f"Transformação por A — Área = |det(A)| = {abs(np.linalg.det(A)):.3f}")
    plt.legend()
    plt.axis('equal')
    plt.savefig("determinante_area.png")
    plt.show()

A = np.array([[2,1],[1,3]])
visualizar_transformacao(A)





det_2x2(A1) = 5
det_2x2(A2) = 0
Sarrus(B1) = 1  | numpy = 0.9999999999999987
Sarrus(B2) = 0  | numpy = 0.0
Determinante = 2.0
Passos = 6
1) det(AB) = 0.503468  | det(A)det(B) = 0.503468
2) det(A^T) = -1.311707  | det(A) = -1.311707
3) det(kA) = -163.963347  | k^n det(A) = -163.963347
4) Row swap → det = 1.311707  | esperado = 1.311707
5) Add múltiplo → det = -1.311707  | esperado = -1.311707

Matriz:
 [[2 1]
 [1 1]]
Invertível: True
Determinante: 1.0
Cond. number: 6.8541019662496865

Matriz:
 [[1 2]
 [2 4]]
Invertível: False
Determinante: 0.0
Cond. number: 2.7556760105735884e+16

Matriz:
 [[1 1]
 [1 1]]
Invertível: False
Determinante: 0.0
Cond. number: 1.3937894790255813e+17
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
Verificação A*A^-1 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
