In [7]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

x = np.array([2,3,4])

resultado = A @ x

a1 = A[:,0]
a2 = A[:,1]
a3 = A[:,2]

comb = x[0]*a1 + x[1]*a2 + x[2]*a3

print("A @ x =")
print(resultado)

print("\nCombinação linear =")
print(comb)

A @ x =
[20 47 74]

Combinação linear =
[20 47 74]


In [6]:
M = np.random.rand(3,3)

S = M + M.T

print("M =")
print(M)

print("\nS = M + M.T =")
print(S)

print("\nS.T =")
print(S.T)

print("\nS é simétrica?")
print((S == S.T).all())

M =
[[0.14541127 0.83980634 0.09392236]
 [0.34135708 0.78898398 0.05340644]
 [0.68218105 0.91455998 0.96790193]]

S = M + M.T =
[[0.29082253 1.18116342 0.7761034 ]
 [1.18116342 1.57796796 0.96796642]
 [0.7761034  0.96796642 1.93580386]]

S.T =
[[0.29082253 1.18116342 0.7761034 ]
 [1.18116342 1.57796796 0.96796642]
 [0.7761034  0.96796642 1.93580386]]

S é simétrica?
True


In [5]:
print("(A.T).T =")
print((A.T).T)

print("\nA =")
print(A)

print("\n(A + B).T =")
print((A + B).T)

print("\nA.T + B.T =")
print(A.T + B.T)

print("\n(A @ C).T =")
print((A @ C).T)

print("\nC.T @ A.T =")
print(C.T @ A.T)

(A.T).T =
[[1 2 3]
 [4 5 6]]

A =
[[1 2 3]
 [4 5 6]]

(A + B).T =
[[7 7]
 [7 7]
 [7 7]]

A.T + B.T =
[[7 7]
 [7 7]
 [7 7]]

(A @ C).T =
[[22 49]
 [28 64]]

C.T @ A.T =
[[22 49]
 [28 64]]


In [4]:
P = np.array([[1,2],
              [3,4]])

Q = np.array([[0,1],
              [1,0]])

print("P @ Q =")
print(P @ Q)

print("\nQ @ P =")
print(Q @ P)

print("\n[P,Q] =")
print(P @ Q - Q @ P)

I = np.eye(2)

print("\nP @ I =")
print(P @ I)

print("\nI @ P =")
print(I @ P)

P @ Q =
[[2 1]
 [4 3]]

Q @ P =
[[3 4]
 [1 2]]

[P,Q] =
[[-1 -3]
 [ 3  1]]

P @ I =
[[1. 2.]
 [3. 4.]]

I @ P =
[[1. 2.]
 [3. 4.]]


In [3]:
C = np.array([[1,2],
              [3,4],
              [5,6]])

print("A @ C =")
print(A @ C)

print("\nC @ A =")
print(C @ A)

A @ C =
[[22 28]
 [49 64]]

C @ A =
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[6,5,4],
              [3,2,1]])

print("A + B =")
print(A + B)

print("\nA - B =")
print(A - B)

print("\n3A =")
print(3 * A)

A + B =
[[7 7 7]
 [7 7 7]]

A - B =
[[-5 -3 -1]
 [ 1  3  5]]

3A =
[[ 3  6  9]
 [12 15 18]]
