In [10]:
import numpy as np

#T1
A = np.array([[1, 2, 3], 
              [0, 1, 4]])

B = np.array([[2, -1, 0], 
              [3, 4, -2]])
        

soma = A + B

subtracao = A - B

escalar_3A = 3 * A

assert soma.shape == A.shape == B.shape

print("\nVerificação de dimensões: OK")

print("Matriz A + B:\n", soma)
print("Matriz A - B:\n", subtracao)
print("Matriz 3A:\n", escalar_3A)

#T2
C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

AC = A @ C
CA = C @ A
print("\nMatriz A @ C:\n", AC)
print("Matriz C @ A:\n", CA)
print("""
Explicação:
AC e CA têm dimensões diferentes porque a multiplicação
de matrizes depende da ordem.

(2x3)*(3x2) -> (2x2)
(3x2)*(2x3) -> (3x3)

Logo, AC != CA em geral.
""")

#T3
P = np.array([
    [1, 2],
    [3, 4]
])

Q = np.array([
    [0, 1],
    [1, 0]
])

I = np.eye(2)

PQ = P @ Q
QP = Q @ P
commutador = PQ - QP

print("\nPQ:")
print(PQ)

print("\nQP:")
print(QP)

print("\nComutador [P,Q] = PQ - QP:")
print(commutador)

print("\nPQ == QP ?", np.allclose(PQ, QP))

print("\nPI:")
print(P @ I)

print("\nIP:")
print(I @ P)

print("\nPI = IP = P ?",
      np.allclose(P @ I, P) and np.allclose(I @ P, P))

#T4

prop1 = np.allclose((A.T).T, A)

prop2 = np.allclose((A + B).T, A.T + B.T)

prop3 = np.allclose((AC).T, C.T @ A.T)

print("(A^T)^T = A :", prop1)
print("(A + B)^T = A^T + B^T :", prop2)
print("(AC)^T = C^T A^T :", prop3)

#T5

np.random.seed(42)
M = np.random.randint(1, 10, (3, 3))

S = M + M.T

print("\nS é simétrica?", np.allclose(S, S.T))

A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

x = np.array([2, -1, 3])

Ax = A @ x

print("\nAx:")
print(Ax)

a1 = A[:, 0]
a2 = A[:, 1]
a3 = A[:, 2]

combinacao_linear = x[0] * a1 + x[1] * a2 + x[2] * a3

print("\nCombinação linear dos vetores coluna de A com os coeficientes de x:")
print(combinacao_linear)
print("\nAx == combinação linear ?", np.allclose(Ax, combinacao_linear))





Verificação de dimensões: OK
Matriz A + B:
 [[3 1 3]
 [3 5 2]]
Matriz A - B:
 [[-1  3  3]
 [-3 -3  6]]
Matriz 3A:
 [[ 3  6  9]
 [ 0  3 12]]

Matriz A @ C:
 [[22 28]
 [23 28]]
Matriz C @ A:
 [[ 1  4 11]
 [ 3 10 25]
 [ 5 16 39]]

Explicação:
AC e CA têm dimensões diferentes porque a multiplicação
de matrizes depende da ordem.

(2x3)*(3x2) -> (2x2)
(3x2)*(2x3) -> (3x3)

Logo, AC != CA em geral.


PQ:
[[2 1]
 [4 3]]

QP:
[[3 4]
 [1 2]]

Comutador [P,Q] = PQ - QP:
[[-1 -3]
 [ 3  1]]

PQ == QP ? False

PI:
[[1. 2.]
 [3. 4.]]

IP:
[[1. 2.]
 [3. 4.]]

PI = IP = P ? True
(A^T)^T = A : True
(A + B)^T = A^T + B^T : True
(AC)^T = C^T A^T : True

S é simétrica? True

Ax:
[ 9 11  4]

Combinação linear dos vetores coluna de A com os coeficientes de x:
[ 9 11  4]

Ax == combinação linear ? True
