In [1]:
import numpy as np

A = np.array([[2,1],
              [1,3]])

b = np.array([8,13])

x = np.linalg.solve(A, b)

print("Solução:")
print(x)

Solução:
[2.2 3.6]


In [2]:
A = np.array([[2,1,8],
              [1,3,13]], dtype=float)

linhas = len(A)

for i in range(linhas):

    A[i] = A[i] / A[i,i]

    for j in range(linhas):
        if i != j:
            A[j] = A[j] - A[j,i] * A[i]

print("Matriz reduzida:")
print(A)

Matriz reduzida:
[[1.  0.  2.2]
 [0.  1.  3.6]]


In [3]:
A1 = np.array([[1,1,2],
               [2,2,5]], dtype=float)

A2 = np.array([[1,1,2],
               [2,2,4]], dtype=float)

print("Sistema impossível:")
print(A1)

print("\nSistema com infinitas soluções:")
print(A2)

Sistema impossível:
[[1. 1. 2.]
 [2. 2. 5.]]

Sistema com infinitas soluções:
[[1. 1. 2.]
 [2. 2. 4.]]


In [4]:
A = np.array([[2,1],
              [1,3]])

b = np.array([8,13])

x = np.linalg.solve(A, b)

print("Solução:")
print(x)

print("\nVerificação:")
print(A @ x)

Solução:
[2.2 3.6]

Verificação:
[ 8. 13.]
